episode_position_changes = {
   "Yellow": {
        1: {"action": 5, "drama": 0, "thriller": 10},
        2: {"action": 0, "drama": 0, "thriller": 5},
        3: {"action": 10, "drama": -5, "thriller": 5},
        4: {"action": 5, "drama": 0, "thriller": 5},
        5: {"action": 0, "drama": 0, "thriller": 10},
        6: {"action": 0, "drama": 0, "thriller": 5},
        7: {"action": 5, "drama": 0, "thriller": 5},
        8: {"action": 5, "drama": 0, "thriller": 10},
    },
    "Green": {
        1: {"action": 5, "drama": 0, "thriller": -5},
        2: {"action": 0, "drama": 5, "thriller": -5},
        3: {"action": 0, "drama": 5, "thriller": 0},
        4: {"action": 5, "drama": 0, "thriller": 0},
        5: {"action": 5, "drama": 5, "thriller": 5},
        6: {"action": 0, "drama": -5, "thriller": 5},
        7: {"action": 0, "drama": -5, "thriller": 10},
        8: {"action": 5, "drama": -5, "thriller": 10},
    },
    "White": {
        1: {"action": -5, "drama": 10, "thriller": -10},
        2: {"action": 0, "drama": 5, "thriller": -5},
        3: {"action": 0, "drama": 5, "thriller": 0},
        4: {"action": 0, "drama": 5, "thriller": 0},
        5: {"action": 0, "drama": 5, "thriller": 5},
        6: {"action": 0, "drama": -5, "thriller": 5},
        7: {"action": 5, "drama": -10, "thriller": 10},
        8: {"action": 5, "drama": -10, "thriller": 10},
    },
    "Violet": {
        1: {"action": 0, "drama": 10, "thriller": -5},
        2: {"action": 5, "drama": 5, "thriller": 0},
        3: {"action": 5, "drama": 0, "thriller": 0},
        4: {"action": 0, "drama": 5, "thriller": 5},
        5: {"action": 0, "drama": 0, "thriller": 5},
        6: {"action": 0, "drama": -5, "thriller": 5},
        7: {"action": 5, "drama": 0, "thriller": 10},
        8: {"action": 5, "drama": -10, "thriller": 10},
    },
    "Pink": {
        1: {"action": 5, "drama": -5, "thriller": 10},
        2: {"action": 0, "drama": -5, "thriller": 10},
        3: {"action": 0, "drama": -5, "thriller": 5},
        4: {"action": 5, "drama": 0, "thriller": 0},
        5: {"action": 0, "drama": 0, "thriller": 0},
        6: {"action": 5, "drama": 5, "thriller": 0},
        7: {"action": 5, "drama": 5, "thriller": -5},
        8: {"action": 0, "drama": 5, "thriller": -5},
    },
    "Red": {
        1: {"action": 10, "drama": -10, "thriller": 10},
        2: {"action": 10, "drama": -5, "thriller": 10},
        3: {"action": 5, "drama": -5, "thriller": 10},
        4: {"action": 5, "drama": 0, "thriller": 5},
        5: {"action": 5, "drama": 0, "thriller": 5},
        6: {"action": 0, "drama": 0, "thriller": 0},
        7: {"action": 0, "drama": 0, "thriller": 5},
        8: {"action": 5, "drama": 0, "thriller": 5},
    },
    "Orange": {
        1: {"action": 0, "drama": 10, "thriller": -5},
        2: {"action": 5, "drama": 5, "thriller": -5},
        3: {"action": -5, "drama": 5, "thriller": 0},
        4: {"action": 5, "drama": 5, "thriller": 5},
        5: {"action": 0, "drama": -5, "thriller": 5},
        6: {"action": -5, "drama": 5, "thriller": 5},
        7: {"action": 5, "drama": 0, "thriller": 5},
        8: {"action": 0, "drama": -5, "thriller": 5},
    },
    "Blue": {
        1: {"action": -5, "drama": 10, "thriller": -5},
        2: {"action": 5, "drama": 0, "thriller": 0},
        3: {"action": 0, "drama": 5, "thriller": 5},
        4: {"action": 0, "drama": 5, "thriller": 5},
        5: {"action": 5, "drama": 5, "thriller": 5},
        6: {"action": 0, "drama": 5, "thriller": 5},
        7: {"action": 5, "drama": -5, "thriller": 5},
        8: {"action": 5, "drama": 0, "thriller": 10},
    }
}